import { useEffect, useState } from "react";
import { Link } from "@tanstack/react-router";
import { Flame, Clock } from "lucide-react";
import {
  ensureTrending,
  fetchMyVotes,
  fetchRecent,
  fetchTrending,
  type RecentNickname,
  type TrendingName,
  type VoteDirection,
} from "@/lib/live";
import { VoteButtons } from "./VoteButtons";
import { useCopy } from "@/hooks/use-copy";
import { track } from "@/lib/analytics";
import { useSelection } from "@/hooks/use-selection";
import { SelectableResults, SelectionControls } from "./SelectableResults";
import { ExportBar } from "./ExportBar";

/** Popularity trends — the most upvoted names across the site. */
export function TrendingPanel({ limit = 12 }: { limit?: number }) {
  const [rows, setRows] = useState<TrendingName[]>([]);
  const [myVotes, setMyVotes] = useState<Record<string, VoteDirection>>({});
  const { copy, copied } = useCopy();

  useEffect(() => {
    void fetchTrending(limit).then(setRows);
    void fetchMyVotes().then(setMyVotes);
  }, [limit]);

  if (!rows.length) return null;

  return (
    <section className="surface-card p-5">
      <h2 className="mb-1 flex items-center gap-2 font-display text-xl font-bold">
        <Flame className="h-5 w-5 text-primary" /> Popularity trends
      </h2>
      <p className="mb-4 text-sm text-muted-foreground">
        The nicknames our visitors copy and upvote most this week. Tap a name to copy it, then vote
        it up or down so the best ideas rise to the top.
      </p>
      <ol className="grid gap-2 sm:grid-cols-2">
        {rows.map((r, i) => (
          <li
            key={r.id}
            className="hover-lift flex items-center gap-2 rounded-lg border border-border bg-background px-3 py-2"
          >
            <span className="w-5 shrink-0 text-xs font-bold text-muted-foreground">{i + 1}</span>
            <button
              type="button"
              onClick={() => {
                copy(r.styled || r.name);
                track("copy", "popularity-trends", { value_length: r.name.length });
              }}
              aria-label={`Copy ${r.styled || r.name}`}
              className="min-w-0 flex-1 truncate text-left font-medium"
            >
              {copied === (r.styled || r.name) ? "Copied!" : r.styled || r.name}
            </button>
            <VoteButtons
              nicknameId={r.id}
              up={r.votes_up}
              down={r.votes_down}
              myVote={myVotes[r.id]}
              size="sm"
            />
          </li>
        ))}
      </ol>
      <Link to="/ideas" className="mt-4 inline-block text-sm font-semibold text-primary hover:underline">
        Browse every name idea →
      </Link>
    </section>
  );
}

/** Live feed of names other visitors just generated. */
export function RecentPanel({ limit = 18 }: { limit?: number }) {
  const [rows, setRows] = useState<RecentNickname[]>([]);
  const [promoted, setPromoted] = useState<Record<string, string>>({});
  const { copy, copied } = useCopy();

  useEffect(() => {
    void fetchRecent(limit).then(setRows);
  }, [limit]);

  if (!rows.length) return null;

  return (
    <section className="surface-card p-5">
      <h2 className="mb-1 flex items-center gap-2 font-display text-xl font-bold">
        <Clock className="h-5 w-5 text-primary" /> Recent nicknames
      </h2>
      <p className="mb-4 text-sm text-muted-foreground">
        Fresh picks generated by visitors moments ago — tap one to copy, or vote to push it into the
        popularity trends.
      </p>
      <ul className="grid gap-2 sm:grid-cols-2">
        {rows.map((r) => (
          <li
            key={r.id}
            className="flex items-center gap-2 rounded-lg border border-border bg-background px-3 py-1.5"
          >
            <button
              type="button"
              onClick={() => {
                copy(r.name);
                track("copy", "recent-nicknames", { value_length: r.name.length });
              }}
              aria-label={`Copy ${r.name}`}
              className="min-w-0 flex-1 truncate text-left text-sm font-medium"
            >
              {copied === r.name ? "Copied!" : r.name}
            </button>
            {promoted[r.id] ? (
              <VoteButtons
                nicknameId={promoted[r.id]!}
                up={0}
                down={0}
                tool="recent-nicknames"
                size="sm"
              />
            ) : (
              <button
                type="button"
                onClick={async () => {
                  const id = await ensureTrending(r.name, r.tool);
                  if (id) setPromoted((p) => ({ ...p, [r.id]: id }));
                }}
                className="shrink-0 rounded-md border border-border px-2 py-1 text-[11px] font-semibold text-muted-foreground hover:border-primary hover:text-primary"
              >
                Vote
              </button>
            )}
          </li>
        ))}
      </ul>
    </section>
  );
}

/** Trending stylised names — individually selectable and exportable. */
export function TrendingStylesCard({ items }: { items: string[] }) {
  const { selected, toggle, selectAll, clear, exportLines, count } = useSelection(items);

  return (
    <div className="surface-card p-5">
      <h2 className="font-display font-bold">Trending styles</h2>
      <p className="mt-1 text-xs text-muted-foreground">
        Tap to copy, tick to export several at once.
      </p>
      <div className="mt-3">
        <SelectableResults
          items={items.map((v) => ({ value: v }))}
          selected={selected}
          onToggle={toggle}
          tool="trending-styles"
          size="sm"
        />
      </div>
      <div className="mt-3 space-y-3">
        <SelectionControls
          total={items.length}
          selectedCount={count}
          onSelectAll={selectAll}
          onClear={clear}
          tool="trending-styles"
        />
        <ExportBar
          lines={exportLines}
          fileBase="trending-styles"
          title="Trending name styles"
          tool="trending-styles"
        />
      </div>
    </div>
  );
}
