import { useEffect, useState } from "react";
import { Link } from "@tanstack/react-router";
import { Flame, Clock } from "lucide-react";
import { fetchRecent, fetchTrending, type RecentNickname, type TrendingName } from "@/lib/live";
import { useCopy } from "@/hooks/use-copy";
import { track } from "@/lib/analytics";
import { useSelection } from "@/hooks/use-selection";
import { SelectableResults, SelectionControls } from "./SelectableResults";
import { ExportBar } from "./ExportBar";

/** Popularity trends — the most upvoted names across the site. */
export function TrendingPanel({ limit = 12 }: { limit?: number }) {
  const [rows, setRows] = useState<TrendingName[]>([]);
  const { copy, copied } = useCopy();

  useEffect(() => {
    void fetchTrending(limit).then(setRows);
  }, [limit]);

  if (!rows.length) return null;

  return (
    <section className="surface-card p-5">
      <h2 className="mb-1 flex items-center gap-2 font-display text-xl font-bold">
        <Flame className="h-5 w-5 text-primary" /> Popularity trends
      </h2>
      <p className="mb-4 text-sm text-muted-foreground">
        The nicknames and styles our visitors copy most this week.
      </p>
      <ol className="grid gap-2 sm:grid-cols-2">
        {rows.map((r, i) => (
          <li key={r.id}>
            <button
              type="button"
              onClick={() => {
                copy(r.styled || r.name);
                track("copy", "popularity-trends", { value_length: r.name.length });
              }}
              className="hover-lift flex w-full items-center gap-3 rounded-lg border border-border bg-background px-3 py-2 text-left"
            >
              <span className="w-5 shrink-0 text-xs font-bold text-muted-foreground">{i + 1}</span>
              <span className="min-w-0 flex-1 truncate font-medium">{r.styled || r.name}</span>
              <span className="shrink-0 text-xs text-muted-foreground">
                {copied === (r.styled || r.name) ? "Copied" : `▲ ${r.votes_up}`}
              </span>
            </button>
          </li>
        ))}
      </ol>
      <Link to="/ideas" className="mt-4 inline-block text-sm font-semibold text-primary hover:underline">
        Browse every name idea →
      </Link>
    </section>
  );
}

/** Live feed of names other visitors just generated. */
export function RecentPanel({ limit = 18 }: { limit?: number }) {
  const [rows, setRows] = useState<RecentNickname[]>([]);
  const { copy, copied } = useCopy();

  useEffect(() => {
    void fetchRecent(limit).then(setRows);
  }, [limit]);

  if (!rows.length) return null;

  return (
    <section className="surface-card p-5">
      <h2 className="mb-1 flex items-center gap-2 font-display text-xl font-bold">
        <Clock className="h-5 w-5 text-primary" /> Recent nicknames
      </h2>
      <p className="mb-4 text-sm text-muted-foreground">
        Fresh picks generated by visitors moments ago — tap any of them to copy.
      </p>
      <ul className="flex flex-wrap gap-2">
        {rows.map((r) => (
          <li key={r.id}>
            <button
              type="button"
              onClick={() => {
                copy(r.name);
                track("copy", "recent-nicknames", { value_length: r.name.length });
              }}
              className="rounded-full border border-border bg-background px-3 py-1.5 text-sm transition-colors hover:border-primary"
            >
              {copied === r.name ? "Copied" : r.name}
            </button>
          </li>
        ))}
      </ul>
    </section>
  );
}

/** Trending stylised names — individually selectable and exportable. */
export function TrendingStylesCard({ items }: { items: string[] }) {
  const { selected, toggle, selectAll, clear, exportLines, count } = useSelection(items);

  return (
    <div className="surface-card p-5">
      <h2 className="font-display font-bold">Trending styles</h2>
      <p className="mt-1 text-xs text-muted-foreground">
        Tap to copy, tick to export several at once.
      </p>
      <div className="mt-3">
        <SelectableResults
          items={items.map((v) => ({ value: v }))}
          selected={selected}
          onToggle={toggle}
          tool="trending-styles"
          size="sm"
        />
      </div>
      <div className="mt-3 space-y-3">
        <SelectionControls
          total={items.length}
          selectedCount={count}
          onSelectAll={selectAll}
          onClear={clear}
          tool="trending-styles"
        />
        <ExportBar
          lines={exportLines}
          fileBase="trending-styles"
          title="Trending name styles"
          tool="trending-styles"
        />
      </div>
    </div>
  );
}
